apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::209202483715:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-11AVV9XP1QQ5V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::209202483715:role/UdacityFlaskDeployCBKubectlRole
      username: build  
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-31T04:29:41Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1130"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0723c028-f308-446c-8d4a-4a26763679ba
